name: garderobelappen
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # connect to dropbox
  #  dropbox_client: ^0.5.3 # this one doesn't support most methods, and uses java/ios native methods that are hard to modify
  restio: ^0.5.2

  random_string: ^2.0.1
  json_annotation: ^3.0.1
  url_launcher: ^5.4.2
  english_words: ^3.1.5
  # used for firebase cloud database
  cloud_firestore: ^0.13.5
  # Used for firebase chat
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.2
  fluttertoast: ^4.0.1
  image_picker: ^0.6.5
  shared_preferences: ^0.5.6+3
  firebase_storage: ^3.1.5
  cached_network_image: 2.0.0-rc.1
  intl: ^0.16.1
  firebase_messaging: 6.0.13
  flutter_local_notifications: 1.4.0
  photo_view: ^0.9.2
  # used for google sheets
  gsheets: ^0.2.1+1
  # gsheetscsv
  flutter_cache_manager: ^1.2.2
  csv: ^4.0.3
  # magiccart (provider - widget notification architecture)
  provider: ^4.0.5
  device_info: ^0.4.2+1
  # hive instead of shared preferences
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # flutter websocket manager
  # websocket_manager: ^0.2.2 # this is a package from github - this package sucks!
  web_socket_channel: ^1.1.0 # this is the official flutter websockets package
  # webrtc
  flutter_webrtc: ^0.2.6
  #duplicated shared_preferences:
  shared_preferences_macos:
  shared_preferences_web:
  http: ^0.12.0+4

  # Required for MediaRecorder example
  path_provider:
  path_provider_macos:
  # flutter geolocator
  geolocator: ^5.3.1
  # stripe
  get_it: ^4.0.2
  #  get_it: ^1.0.3+2
  cloud_functions: ^0.4.1
  stripe_sdk: ^2.8.1







  garderobel_api:
    #   #     path: ./../garderobel_api
    git:
      url: https://github.com/allanchao/glappen-firebase-client.git
    #      url: git@bitbucket.org:garderobelapp/garderobel_api.git # bitrise
    #       url: git://bitbucket.org:garderobelapp/garderobel_api.git
    #       url: https://ezet@bitbucket.org/garderobelapp/garderobel_api.git

    #  stripe_sdk: ^2.3.0
    #  stripe_sdk:
  #    path: ./../stripe_sdk
  #    git:
  #      url: git://github.com/ezet/stripe_sdk.git

  easy_localization: ^2.2.1

  firebase_ui: ^1.0.8
  firebase_core: ^0.4.4+3

  uni_links: ^0.2.0

  #  qr_code_scanner: ^0.0.10
  #  barcode_scan: ^1.0.0
  qr_mobile_vision: ^1.0.1+1

  flutter_swiper: ^1.1.6
















dev_dependencies:
  flutter_test:
    sdk: flutter
  image_test_utils: ^1.0.0
  build_runner: ^1.8.1
  json_serializable: ^3.3.0
  # test: ^1.14.2
  # hive instead of shared preferences
  hive_generator: ^0.7.0+2

dependency_overrides:
  crypto: 2.1.4 # needed for both restio and flutter_test https://github.com/tiagohm/restio/issues/3

  firebase_auth: 0.16.0 # needed to resolve
  # Because garderobelappen depends on firebase_ui ^1.0.8 which depends on firebase_auth ^0.14.0+5, firebase_auth ^0.14.0+5 is required.
  # So, because garderobelappen depends on firebase_auth ^0.16.0, version solving failed.
  # pub get failed (1; So, because garderobelappen depends on firebase_auth ^0.16.0, version solving failed.)
  cloud_firestore: ^0.13.5
  # Because garderobelappen depends on garderobel_api from git which depends on cloud_firestore ^0.12.7, cloud_firestore ^0.12.7 is required.
  intl: ^0.16.1
    #Because easy_localization >=2.1.0+1 depends on flutter_localizations any from sdk which depends on intl 0.16.0, easy_localization >=2.1.0+1 requires intl 0.16.0.
  #
  #So, because flutterapp depends on both intl ^0.16.1 and easy_localization ^2.2.1, version solving failed.
  #pub get failed (1; So, because flutterapp depends on both intl ^0.16.1 and easy_localization ^2.2.1, version solving failed.)

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/scheckout.html
    - icons/amex.png
    - icons/discover.png
    - icons/mastercard.png
    - icons/visa.png
    - assets/l8n/en-US.json
    - assets/l8n/nb-NO.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
